-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

---

- - Schema estoque

---

---

- - Schema estoque

---

CREATE SCHEMA IF NOT EXISTS estoque DEFAULT CHARACTER SET utf8 ;
USE estoque ;

---

- - Table estoque.produtos

---

DROP TABLE IF EXISTS estoque.produtos ;

CREATE TABLE IF NOT EXISTS estoque.produtos (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
valor DECIMAL(10,2) NOT NULL,
quantidade INT NOT NULL,
categoria VARCHAR(200) NOT NULL,
PRIMARY KEY (id))
ENGINE = InnoDB;

---

- - Table estoque.movimentacoes

---

DROP TABLE IF EXISTS estoque.movimentacoes ;

CREATE TABLE IF NOT EXISTS estoque.movimentacoes (
id INT NOT NULL AUTO_INCREMENT,
dt DATETIME NOT NULL,
tipo VARCHAR(200) NOT NULL,
quantidade INT NOT NULL,
produtos_id INT NOT NULL,
PRIMARY KEY (id),
INDEX fk_movimentacoes_produtos_idx (produtos_id ASC) VISIBLE,
CONSTRAINT fk_movimentacoes_produtos
FOREIGN KEY (produtos_id)
REFERENCES estoque.produtos (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS